.travis.yml, docs/Makefile
This asks travis to build the documentation as part of a PR so we can see if it works before merging.
=> Add travis setup to build documentation during PRs

.travis.yml, README.md, earthpy/tests/test_spatial.py, environment.yml
Ok @lwasser! This PR adds support for testing the earthpy package on Travis CI, and uploads code coverage reports onto Codecov upon successful builds. 
Tests are contained in the `earthpy/tests/` directory, and for starters I've added just one test to get going. To run these tests locally, you can run `pytest` from the command line (the `environment.yml` file has been updated to install the pytest package, so you may need to update your environment). I spent a fair bit of time comparing testing frameworks, and pytest seems to be one of the better ones (simple to use but powerful when you need it to be).
=> Support testing on Travis CI + Codecov

docs/spatial-raster.rst, earthpy/spatial.py
Added the arr_out parameter to the spatial-raster.rst file.
Added the arr_out parameter to spatial.py.
Formatted comments in spatial.py to be PEP8 style.
Replaced internal dialogue comments to be TODOs instead. Made these comments more clear.
Deleted some unnecessary comments.
@mbjoseph 
See posted issue here: https://github.com/earthlab/earthpy/issues/51
=> Adding arr_out parameter to spatial-raster.rst and formatting comments

docs/get-started.rst, earthpy/spatial.py
This pull request addresses issue #67 
Unused unit tests and commented code lines are deleted from spatial.py
The file get-started.rst now includes descriptions of each of the three modules and converts them to list form.
=> Clarify module descriptions in rst AND delete unused file path checks, context managers, and input type checks in spatial.py

docs/spatial-raster.rst, earthpy/spatial.py
@lwasser Added documentation for draw_legend functon to spatial-raster.rst and fixed misspelling of the word 'output' in stack_raster_tifs code in spatial.py.  While reviewing the code for the draw_legend function in spatial.py, I also noticed that the word 'unique' was misspelled.  I did not see a reported issue for that elsewhere so I went ahead and fixed that as well. These updates are for the items listed in this issue: https://github.com/earthlab/earthpy/issues/63
=> Add .rst file documentation for the draw_legend function and fix two misspellings in spatial.py

docs/index.rst, docs/spatial-raster.rst
Reworded spatial-raster.rst lines 9-11:
```
The ``stack_raster_tifs`` function turns a list of raster paths into:
1. a stacked geotiff on your hard drive and
2. (optional) an output raster stack in numpy format with associated metadata.
```
3. Added summary description of each document in earthpy to index.rst
=> Reword content in spatial-raster.rst and Add summary description of earthpy to index.rst

earthpy/io.py
This extends the data loader so that you can pass it a URL instead of a predefined key.
```python
In [2]: d = EarthlabData("/tmp/ea")
In [3]: d.get_data(url="https://ndownloader.figshare.com/files/10960109")
```
will create a directory called `/tmp/ea/unsorted/cold-springs-fire/` which contains the unzipped contents of the file from the URL. It tries its best to guess what the file type is and what to name things.
=> Extend data loader to fetch arbitrary URLs

.coveragerc, README.md, earthpy/tests/conftest.py, earthpy/tests/test_clip.py, earthpy/tests/test_mask.py, earthpy/tests/test_spatial.py
Our original idea was to add a utility functions script to the tests directory, and then use those utility functions in test modules to simulate fake data. But the best practice for pytest seems instead to use fixtures, which are functions that generate objects required for tests to run. Each test takes fixture names as arguments, and then executes those fixture functions to create fake data independent for each test. Creating the data independently for each test is more robust than creating shared data in a global environment that is used by multiple tests. 
Fixtures used by multiple test modules are defined in `earthpy/tests/conftest.py`. 
I found these links on fixtures to be helpful in wrapping my head around the concept: 
- https://docs.pytest.org/en/latest/fixture.html
- …
=> Adding pytest fixtures for re-used test data

.travis.yml
@lwasser This PR should force Travis to print the output from `conda list` after activating the environment. That way we can see what versions of each package are installed in Travis for debugging.
=> List package versions in Travis

earthpy/tests/test_clip.py
Previously we had a test called `check_input_gdfs` in the `test_clip.py` module that did not execute: https://codecov.io/gh/earthlab/earthpy/src/master/earthpy/tests/test_clip.py#L39...42 
It never ran because it was not prefixed with `test_*`. This pull request updates the test's name so that it actually runs, and fixes an error in the test (previously we had expected an `AssertionError`, but really we need an `AttributeError`). 
One lesson here is that inspecting code coverage **of the tests** is useful to ensure that tests are actually executed.
=> Fix test that previously did not run

.pre-commit-config.yaml, CONTRIBUTING.rst, dev-requirements.txt, pyproject.toml
This adds `black` as a pre-commit hook.
I followed the link to the blog post Joe linked to and then ended up on https://github.com/ambv/black#version-control-integration which uses the same tool (`pre-commit`) to set things up. Conclusion: I just followed the instructions 😄.
I didn't add `flake8` as a pre-commit hook as I think `black` will reformat changes you made that would violate pep8 in black's steamroller way of dealing with things.
Closes #132
=> Add black as a pre-commit hook

.travis.yml, setup.py
This PR will run black on Travis CI to verify that the pre-commit hook has been used locally. It should fail any builds that have commits that black would change, as suggested in https://github.com/earthlab/earthpy/issues/166. 
I am going to push a commit to this branch that should break the build to verify before merging.
=> Run black on Travis CI

.travis.yml, earthpy/__init__.py, earthpy/spatial.py, earthpy/tests/conftest.py, earthpy/tests/test_io.py, earthpy/tests/test_spatial.py, setup.cfg, setup.py
This PR adds unit tests for `crop_image`, with fixtures [borrowed from rasterio](https://github.com/mapbox/rasterio/blob/master/tests/conftest.py) that create raster files and geometries. These eliminate the need for our previous function that would write GeoTIFFs for testing. Using fixtures is more robust, because each test gets its own tif file, and we can leverage some of the existing testing logic developed by the rasterio team. 
Last, as part of working with these fixtures, this PR includes a file `setup.cfg` which tells pytest to ignore a warning that rasterio creates when using the identity affine geotransform.
Closes #70
=> Add unit tests for crop_image

earthpy/tests/test_spatial.py
Pytest has deprecated the `message` argument, and suggests to use the `match` argument instead. Closes  #192
=> Fix message deprecation

CONTRIBUTING.rst, Makefile
This PR adds prerequisites to the recipe for making docs, so that the command make docs with execute only when necessary (when files in the prerequisites have changed). This also adds a smidgen more information to the CONTRIBUTING.rst file for how to force a rebuild.
@lwasser have a look at the changes to Makefile here, which will ensure that Make behaves in the way that we want (only rebuilding docs when necessary).
Closes #198
=> Add prereqs for make docs

earthpy/tests/test_io.py
This fixes some tests that broke due to rasterio changing the way CRS objects are represented. @lwasser have a look!
=> Use rasterio.crs.CRS to test rasterio crs values

earthpy/io.py
Dag-gum pysal changed the location of their examples, which led to a broken link. This PR removes the link so that our build is robust to PySAL moving files around.
=> Remove pysal link

.travis.yml, CONTRIBUTING.rst, dev-requirements.txt, setup.cfg
This PR adds bumpversion as a way to increment versions programmatically, and also adds a skeleton to the Travis build that will automatically deploy new versions of earthpy to PyPI. See the changes in CONTRIBUTING.rst for instructions on how to deploy.
One thing that still needs to be added to this branch @lwasser is your encrypted PyPI password on this line: https://github.com/earthlab/earthpy/compare/add-bumpversion?expand=1#diff-354f30a63fb0907d4ad57269548329e3R43
Instructions for encrypting your password can be found here: https://docs.travis-ci.com/user/deployment/pypi/
@lwasser it would be good if you added your encrypted password to this branch before merging. Note that if your PyPI password contains special characters you need to escape them before encrypting your password.
=> Add bumpversion and automate PyPI deployment

.zenodo.json
@lwasser This change updates the license name in the zenodo.json file to match the valid value provided by Zenodo for BSD-3-Clause.
=> Update license ID in zenodo.json

CONTRIBUTING.rst, Makefile, earthpy/plot.py, earthpy/spatial.py
This PR adds to our contributing guidelines more detail about deployment, using doctest, and using the Matplotlib plot directive. Solves #222 and #196. 
It also removes the ELLIPSIS calls, which were redundant (doctest enables the use of `...` by default), which results in cleaner examples. 
@lwasser please have a look and see what you think!
=> Adding more info on deployment, doctest, and plots 

.gitignore, setup.py
This PR removes the installation dependency on numpy's distutils module, and instead uses setuptools as recommended by the PSF: https://packaging.python.org/guides/tool-recommendations/
The use of numpy's distutils module seems to be unnecessary for earthpy, because it does not use the specialized features in `numpy.distutils` (e.g., the ability to handle Fortan source files as described here: https://docs.scipy.org/doc/numpy-1.14.0/f2py/distutils.html)
Locally, this solved  #206 for me. I'm opening this as a draft to see how the builds shake out on Travis. I also would like to have other folks (@lwasser and @joemcglinchy if you have time) test this on Mac and Windows if possible, to make sure that the installation still proceeds as expected given the changes to `setup.py`.
=> Use setuptools in setup.py

.gitignore, .travis.yml, CONTRIBUTING.rst, README.md, appveyor.yml, dev-requirements.txt, earthpy/tests/test_plot_rgb.py, earthpy/utils.py, environment.yml, setup.py, tox.ini
This tests earthpy against python 3.5 through 3.7 using tox, and also uses AppVeyor to test earthpy on Windows. Last, this updates documentation for development using conda or virtualenv and testing of multiple python versions with tox.
@lwasser and @joemcglinchy please take the updated development instructions in `CONTRIBUTING.rst` for a test drive. I will be curious to see what issues come up, especially on Windows. I'm opening this as a draft PR until we get some more eyes on it.
Solves the hardest part of #228 - testing on Windows (but we should leave that issue open until we get some tests in CI for macOS). Closes #213.
=> Use tox and AppVeyor

earthpy/io.py
@lwasser  This update adds the URL to the Rim Fire data hosted on Figshare.
=> Add URL to Rim Fire data

CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.rst, docs/code-of-conduct.rst, docs/conf.py, docs/index.rst
This PR adds a code of conduct based on http://contributor-covenant.org and links to it from the CONTRIBUTING guidelines.
This PR also has some capitalization corrections in the docs to consistently use title case for page names. @lwasser please take a look when you get a chance and let me know if this is what you had in mind, or if you think we should make any changes to the code of conduct. 
Closes #27.
=> Add code of conduct

setup.py
Currently because of the way setuptools distributes data and uses the `include_package_data` argument, installing earthpy from PyPI does not seem to consistently include the example data directory as described in https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute. 
This PR solves #250 and #245, and should ensure that installing earthpy with pip includes example data.
=> Remove line for including package data to fix PyPI install issue

CHANGELOG.md, earthpy/tests/test_plot.py, earthpy/tests/test_plot_draw_legend.py, earthpy/tests/test_plot_rgb.py
This PR should address the warning associated with open figures in matplotlib. Essentially `.close` closes any open windows and `.clf` clears the actual figure.
```
earthpy/tests/test_plot_rgb.py::test_stretch_output_scaled
/Users/leahwasser/anaconda3/envs/earthpy-dev/lib/python3.6/site-packages/matplotlib/pyplot.py:514: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
max_open_warning, RuntimeWarning)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
=> Clean up Plots in all tests

.gitignore, CHANGELOG.md, dev-requirements.txt, earthpy/__init__.py, earthpy/io.py, earthpy/tests/test_io.py, earthpy/tests/test_plot.py, earthpy/tests/test_plot_draw_legend.py, earthpy/tests/test_plot_rgb.py
This PR adds unit tests for the `EarthlabData` class. 
**Details**
- This also adds the pytest-vcr package as a dev requirement. To adequately test the `EarthlabData` class, we need to use the internet to see whether files exist, ensure files download, etc. The pytest-vcr package ensures that these downloads only happen once, using the @pytest.mark.vcr decorator for tests. More info can be found here: https://pytest-vcr.readthedocs.io/en/latest/ and some higher level conceptual background is here: https://vcrpy.readthedocs.io/en/latest/
- This PR cleans up unused and unnecessary imports in `earthpy/__init__.py`.
- The documentation for the `EarthlabData` class has been expanded as part of this PR. There are now examples of usage, and some attempts to warn users that the default behavior …
=> Test EarthlabData class

earthpy/mask.py
This addresses [this issue](https://github.com/earthlab/earthpy/issues/276)
This  issue is bizarre as you wouldn't not expect a parameter input to be MODIFIED via an earthpy function but in this case, the input QA layer is actually modified in the function into a boolean.
To avoid this behavior, i've created a copy of the input parameter so the user doesn't get any surprises.
=> fixing bug in mask

.travis.yml, .travis/install.sh, .travis/test.sh, CHANGELOG.md, tox.ini
This PR adds support for OS X testing in our Travis build. This uses conda to set up the dependencies, which is probably going to be the most common use case for mac users. 
With this PR, we will have testing on linux, OS X, and Windows. Closes #228.
=> Test earthpy on OS X with Travis CI

MANIFEST.in, setup.py
Solves #298, and will help us get EarthPy on conda-forge. 
@lwasser if this looks good to you, please merge! 
We will also need to deploy a patch to PyPI after merging this to ensure that the conda-forge build has access to the LICENSE file, which it needs for the earthpy recipe. 
This PR also specifies a url in `setup.py` to make it easier for people to find the repo's webpage from the source code.
=> Use a MANIFEST.in file to distribute the LICENSE and README

earthpy/tests/conftest.py, earthpy/tests/test_clip.py, earthpy/tests/test_crop_image.py, earthpy/tests/test_extent_to_json.py, earthpy/tests/test_norm_diff.py, earthpy/tests/test_plot_bands.py, earthpy/tests/test_stack.py
This PR addresses https://github.com/earthlab/earthpy/issues/219  and #218 
it includes:
1. cleanup of `conftest.py` file to ensure only fixtures used across multiple functions are included
2. splitting up the `test_spatial.py` file into function specific test files.
In this cleanup process, i noticed that the extent_to_json() function has ALL TESTS in one giant function. So that is cleaned up as well.
=> Test Cleanup & Re-org

CHANGELOG.md, earthpy/plot.py, earthpy/tests/test_plot_rgb.py
well it turns out that i missed yet another bug in plot_rgb.
This fix addresses the issue that when you attempt to create a multi-panel plot, this function was plotting the FIRST plot and the rest of the panels were empty. This was because we decided to add `plt.show()` to the function call.
@mbjoseph  when you look at this PR you'll notice there is now some redundant code in the last statement where the plot is generated. 
If we don't want that code, we need to 
1. drop the `plt.show()` call altogether. 
i could be convinced to do this given the function returns the ax object which "prints" as a returned item. or we leave it nice and clean and it just plots for the user by default UNLESS they are creating a more involved plot. 
Note that in this i'm adding a second test that tests a …
=> Another bug fix in plot rgb

.zenodo.json
Creating a distinction between "Creators" and "contributors"
=> Zenodo update -- creator vs contributor

dev-requirements.txt
geopandas should install pandas but also pandas is a part of anaconda.
this should address #358
=> pandas is a redundant requirement for earthpy

appveyor.yml
Essentially this happened for matplotcheck as well. Because earthpy is installing locally via python, it tries to reinstall all of the dependencies. this causes issues. but all of those deps are in our envt so it's unneccesary. installing via pip without the dependencies should make appveyor happy.
=> fix appveyor fail by installing earthpy without the deps

setup.py
It's imported by earthpy.io but not specified in the setup script, so `pip install earthpy` in a new fresh python environment doesn't quite work. This PR takes care of that.
=> Add requests to setup requirements

README.md
This PR addresses #432 created by @sgillies . Earthpy has a dep on the rtree library which requires libspatialindex. this dependency does not install via pip and thus could cause issues for users. 
In the readme, I've added instructions which tell the user to install via conda if they can. this is the use case for most of our students given they use conda so it seems reasonable. 
I've also added a statement associated with earthpy being inspired by the R raster and sp packages which should address #433 
@mbjoseph can you have a look at this PR when you have a chance? @sgillies please let me know if these changes are what you had in mind or if you'd like to see a bit more!!
=> Update readme with conda vs pip instructions

.pre-commit-config.yaml, .travis.yml, README.md, dev-requirements.txt, tox.ini
ok a few notes on this pr
it was supposed to be a simple update but it turns out that there are some issues with pyproj which needs pip>= 19.0 to install properly. as a fix i adjust the deps to specify the min version of pip and also adjusted the tox envt for black to ensure pip was being used to install earthpy.
Just a note that this setup actually seems a bit redundant to me as in the tox envt earthpy is being installed aGAIN from what i can see. i suspect we could make our build faster by just running black in the main earthpy py 3.7 build... but for now i'm just fixing things
=> fix black and also badge order on readme

README.md
:wave: @lwasser - this PR does two things:
1. Updates the preferred citation for the package to link to the JOSS paper.
2. Removes the Zenodo DOI badge - rationale that this is likely to cause confusion to users, especially if you want to encourage citation of the paper rather than a Zenodo DOI?
=> Suggested updates to README

examples/plot_clip.py
I am not sure how this has been passing all of this time but this PR fixes the vignette that's breaking everything. When there are empty geometries things go bonkers and plotting breaks. Fix is using `is_emtpy`. easy enough! Come on travis, be a happy little CI robot. 
this addresses #475
=> fix clip vignette - remove empty geoms

README.md
The link was pointing to the Pandera review (# 12) instead of the EarthPy review (# 3).
=> Fix link to pyOpenSci review in README badge

CHANGELOG.md, earthpy/io.py
This pr addresses #512 which specifically relates to twitter data. since the data are not zipped they needed to be entered into earthpy differently to ensure they were downloaded as files.
=> BUG FIX: fix twitter-flood data key

earthpy/spatial.py
Addresses #483 to improve docstring for `spatial.crop_image()`. Changes:
1. changes description of raster input parameter from `a raster object` to `a rasterio.io.DatasetReader object` to be more accurate
2. While the initial issue requested removal of line 373(`src_image = raster.read()`) followed by retrieval of the `shape` attribute directly from the `raster` object, this does not produce the expected output. `raster` is of type `rasterio.io.DatasetReader` and the `shape` attribute does not return the number of bands present in the dataset (returns `(373, 485)`, but expects `(3, 373, 485)`. For now I've left line 373 in, but changed the names of variables in the vignette to be consistent with other vignettes in `earthpy` and a bit more descriptive:
`raster` --> `src` : this matches …
=> update docstring for crop_image

earthpy/spatial.py, earthpy/tests/test_epsg.py
Adding changes to the crs_check function requested in https://github.com/earthlab/earthpy/pull/707
=> Update crs_check with fixes

.github/workflows/lint-docs.yml
Fixed Linting tests to run both black and flake8 instead of running flake8 twice. Resolving [issue #714](https://github.com/earthlab/earthpy/issues/714). @lwasser @nkorinek
=> Fix Linting tests
